
type = "service_account"
project_id = "smartcertificados-app"
private_key_id = "f70666baa6526388bba11f8be3d28aac3ded1cd8"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQD...
-----END PRIVATE KEY-----"""
client_email = "streamlit-sheets-access@smartcertificados-app.iam.gserviceaccount.com"
client_id = "100496518385409968410"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets-access%40smartcertificados-app.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
